// WinSubst application.
// Copyright (c) 2004-2005 by Elijah Zarezky,
// All rights reserved.

// stdafx.h - include file for standard system include files

// initially generated by AfxScratch v1.0.2297 on 25.07.2004 at 13:26:11
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#if !defined(__stdafx_h)
#define __stdafx_h

#if defined(_MSC_VER) && (_MSC_VER > 1000)
#pragma once
#endif	// _MSC_VER

// unreferenced inline/local function has been removed
#pragma warning(disable: 4514)
// function not inlined
#pragma warning(disable: 4710)
// identifier was truncated in the debug information
#pragma warning(disable: 4786)

// MFC headers
#include <afxwin.h>			// MFC core and standard components
#include <afxcmn.h>			// MFC common control classes

// ATL headers
#include <atlbase.h>

// PSDK headers
#include <shlobj.h>
#include <shlwapi.h>			// light-weight utility APIs

// additional headers
#include "../../SubstSvc/Source/ServiceInterop.h"
#include "../../../Repository/AfxGadgets/Source/SortingListCtrl.h"
#include "../../../Repository/AfxGadgets/Source/Win32Error.h"
#include "../../../Repository/CodeProject/Source/FolderDlg.h"

// force ISO/IEC 14882 conformance in for loop scope
#if _MSC_VER < 1300
#define for if(false); else for
#else
#pragma conform(forScope, on)
#endif	// _MSC_VER

#endif	// __stdafx_h

// end of file
