// SubstSvc NT service.
// Copyright (c) 2004-2005 by Elijah Zarezky,
// All rights reserved.

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// ExecLogging.h - interface of the execution logging

// initially generated by AfxScratch v1.0.2290 on 18.07.2004 at 11:12:43
// visit http://zarezky.spb.ru/projects/afx_scratch.html for more info

#if !defined(__ExecLogging_h)
#define __ExecLogging_h

#if defined(_MSC_VER) && (_MSC_VER > 1000)
#pragma once
#endif	// _MSC_VER

// logging level
enum LOG_LEVEL
{
	LL_NONE		= 0,
	LL_MINIMAL	= 1,
	LL_NORMAL	= 2,
	LL_VERBOSE	= 3
};

void LogFile_Create(LPCTSTR pszFileName);
void LogFile_WriteEntry(LOG_LEVEL eLevel, LPCTSTR pszFormat, ...);
void LogFile_WriteEntry(LOG_LEVEL eLevel, UINT idsFormat, ...);
int LogFile_WriteDbgRpt(int fnType, char* pszMessage, int* pnRetVal);

#endif	// __ExecLogging_h

// end of file
