// SubstSvc NT service.
// Copyright (c) 2004 by Elijah Zarezky,
// All rights reserved.

// ExecLogging.h - interface of the executive logging
// initially generated by AfxScratch 1.0.2290 on 18.07.2004 at 11:12:43

#if !defined(__Logging_h)
#define __Logging_h

// logging level
enum LOG_LEVEL {
	LL_NONE		= 0,
	LL_MINIMAL	= 1,
	LL_NORMAL	= 2,
	LL_VERBOSE	= 3
};

void CreateLogFile(LPCTSTR pszFileName);
void WriteLogFileEntry(LOG_LEVEL eLevel, LPCTSTR pszFormat, ...);
int WriteLogFileDbgRpt(int fnType, char* pszMessage, int* pnRetVal);

#endif	// __Logging_h

// end of file
