// SubstSvc NT service.
// Copyright (c) 2004 by Elijah Zarezky,
// All rights reserved.

// stdafx.cpp - source file that includes just the standard includes
// initially generated by AfxScratch 1.0.2290 on 18.07.2004 at 11:12:43

#include "stdafx.h"

#if defined(_DEBUG)
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#define new DEBUG_NEW
#endif	// _DEBUG

// shared globals
TCHAR g_szServiceName[] = _T("Substituted Drives Manager");
SERVICE_STATUS_HANDLE g_hServiceStatus = NULL;
DWORD g_dwServiceState = SERVICE_STOPPED;

// import libraries
#pragma comment(lib, "shlwapi.lib")

// linker options
#pragma comment(linker, "/ignore:4089")		// all references to DLL discarded by /opt:ref

// entry-point symbol for the Unicode builds
#if defined(UNICODE) || defined(_UNICODE)
#pragma comment(linker, "/entry:wmainCRTStartup")
#endif	// UNICODE

// end of file
