// WinSubst application.
// Copyright (c) 2004 by Elijah Zarezky,
// All rights reserved.

// MainDialog.cpp - implementation of the CMainDialog class
// initially generated by AfxScratch 1.0.2297 on 25.07.2004 at 13:26:11

#include "stdafx.h"
#include "SubstsList.h"
#include "MainDialog.h"
#include "Resource.h"
#include "WinSubstApp.h"

#if defined(_DEBUG)
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#define new DEBUG_NEW
#endif	// _DEBUG

// object model
IMPLEMENT_DYNAMIC(CMainDialog, CDialog)

// message map
BEGIN_MESSAGE_MAP(CMainDialog, CDialog)
	ON_WM_CLOSE()
	ON_NOTIFY(LVN_ITEMCHANGED, IDC_LIST_SUBSTS, OnSubstsListItemChanged)
	ON_BN_CLICKED(IDC_BUTTON_EXIT, OnButtonExit)
END_MESSAGE_MAP()

CMainDialog::CMainDialog(CWnd* pParentWnd):
CDialog(IDD_MAIN, pParentWnd),
m_hIcon(NULL),
m_hSmIcon(NULL),
m_iDefIcon(-1)
{
	CWinSubstApp* pApp = DYNAMIC_DOWNCAST(CWinSubstApp, AfxGetApp());
	ASSERT_VALID(pApp);

	// load dialog's icons
	m_hIcon = pApp->LoadIcon(IDI_APP_ICON);
	m_hSmIcon = pApp->LoadSmIcon(MAKEINTRESOURCE(IDI_APP_ICON));

	// prepare image list
	int cxSmIcon = ::GetSystemMetrics(SM_CXSMICON);
	int cySmIcon = ::GetSystemMetrics(SM_CYSMICON);
	m_imageList.Create(cxSmIcon, cySmIcon, ILC_COLOR16 | ILC_MASK, 8, 8);
	HICON hIcon = pApp->LoadSmIcon(MAKEINTRESOURCE(IDI_DRIVE_ICON));
	m_iDefIcon = m_imageList.Add(hIcon);
	::DestroyIcon(hIcon);
}

CMainDialog::~CMainDialog(void)
{
	m_imageList.DeleteImageList();
	::DestroyIcon(m_hSmIcon);
	::DestroyIcon(m_hIcon);
}

BOOL CMainDialog::OnInitDialog(void)
{
	CDialog::OnInitDialog();

	// set dialog's icons
	SetIcon(m_hIcon, TRUE);
	SetIcon(m_hSmIcon, FALSE);

	DWORD fdwExStyle = m_listSubsts.GetExtendedStyle();
	m_listSubsts.SetExtendedStyle(fdwExStyle | LVS_EX_FULLROWSELECT);
	m_listSubsts.SetImageList(&m_imageList, LVSIL_SMALL);
	m_listSubsts.InsertColumns();
	try {
		m_listSubsts.ListSubstitutions();
	}
	catch (CWin32Error* pXcpt) {
		pXcpt->ReportError(MB_ICONSTOP | MB_OK);
		delete pXcpt;
	}

	if (m_listSubsts.GetItemCount() > 0) {
		m_listSubsts.SortItems(CSubstsList::I_DRIVE, CSubstsList::SORT_ASCENDING);
		m_listSubsts.SetItemState(0, LVIS_SELECTED | LVIS_FOCUSED, 0xFFFFFFFF);
	}
	else {
		GetDlgItem(IDC_BUTTON_CHANGE_SUBST)->EnableWindow(FALSE);
		GetDlgItem(IDC_BUTTON_DELETE_SUBST)->EnableWindow(FALSE);
	}

	// initialized
	return (TRUE);
}

void CMainDialog::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);

	DDX_Control(pDX, IDC_LIST_SUBSTS, m_listSubsts);
}

void CMainDialog::OnOK(void)
{
	// don't invoke inherited handler to avoid dialog closing
}

void CMainDialog::OnCancel(void)
{
	// don't invoke inherited handler to avoid dialog closing
}

void CMainDialog::OnClose(void)
{
	EndDialog(IDCANCEL);
}

void CMainDialog::OnSubstsListItemChanged(NMHDR* /*pHdr*/, LRESULT* pnResult)
{
	BOOL fEnable = m_listSubsts.GetSelectedCount() > 0;
	GetDlgItem(IDC_BUTTON_CHANGE_SUBST)->EnableWindow(fEnable);
	GetDlgItem(IDC_BUTTON_DELETE_SUBST)->EnableWindow(fEnable);
	*pnResult = 0;
}

void CMainDialog::OnButtonExit(void)
{
	EndDialog(IDCANCEL);
}

#if defined(_DEBUG)

void CMainDialog::AssertValid(void) const
{
	// first perform inherited validity check...
	CDialog::AssertValid();
	// ...and then verify our own state as well
	ASSERT_VALID(&m_imageList);
	ASSERT_VALID(&m_listSubsts);
}

void CMainDialog::Dump(CDumpContext& dumpCtx) const
{
	try {
		// first invoke inherited dumper...
		CDialog::Dump(dumpCtx);
		// ...and then dump own unique members
		dumpCtx << "m_hIcon = " << m_hIcon;
		dumpCtx << "\nm_hSmIcon = " << m_hSmIcon;
		dumpCtx << "\nm_imageList = " << m_imageList;
		dumpCtx << "\nm_iDefIcon = " << m_iDefIcon;
		dumpCtx << "\nm_listSubsts = " << m_listSubsts;
	}
	catch (CFileException* pXcpt) {
		pXcpt->ReportError();
		pXcpt->Delete();
	}
}

#endif	// _DEBUG

// end of file
