// WinSubst application.
// Copyright (c) 2004 by Elijah Zarezky,
// All rights reserved.

// MainDialog.h - interface of the CMainDialog class
// initially generated by AfxScratch 1.0.2297 on 25.07.2004 at 13:26:11

#if !defined(__MainDialog_h)
#define __MainDialog_h

class CMainDialog: public CDialog
{
	DECLARE_DYNAMIC(CMainDialog)
	DECLARE_MESSAGE_MAP()

// construction/destruction
public:
	CMainDialog(CWnd* pParentWnd = NULL);
	virtual ~CMainDialog(void);

// overridables
public:
	virtual BOOL OnInitDialog(void);

// attributes
public:
	HICON m_hIcon;
	HICON m_hSmIcon;

// diagnostic services
#if defined(_DEBUG)
public:
	virtual void AssertValid(void) const;
	virtual void Dump(CDumpContext& dumpCtx) const;
#endif
};

#endif	// __MainDialog_h

// end of file
