// WinSubst application.
// Copyright (c) 2004 by Elijah Zarezky,
// All rights reserved.

// stdafx.h - include file for standard system include files
// initially generated by AfxScratch 1.0.2297 on 25.07.2004 at 13:26:11

#if !defined(__stdafx_h)
#define __stdafx_h

// unreferenced inline/local function has been removed
#pragma warning(disable: 4514)
// function not inlined
#pragma warning(disable: 4710)
// identifier was truncated in the debug information
#pragma warning(disable: 4786)

// MFC headers
#include <afxwin.h>			// MFC core and standard components

#endif	// __stdafx_h

// end of file
