// WinSubst application.
// Copyright (c) 2004 by Elijah Zarezky,
// All rights reserved.

// WinSubstApp.h - interface of the CWinSubstApp class
// initially generated by AfxScratch 1.0.2297 on 25.07.2004 at 13:26:11

#if !defined(__WinSubstApp_h)
#define __WinSubstApp_h

class CWinSubstApp: public CWinApp
{
	DECLARE_DYNAMIC(CWinSubstApp)
	DECLARE_MESSAGE_MAP()

// construction/destruction
public:
	CWinSubstApp(void);
	virtual ~CWinSubstApp(void);

// operations
public:
	HICON LoadSmIcon(LPCTSTR pszResName);

// overridables
public:
	virtual BOOL InitInstance(void);

// diagnostic services
#if defined(_DEBUG)
public:
	virtual void AssertValid(void) const;
	virtual void Dump(CDumpContext& dumpCtx) const;
#endif
};

#endif	// __WinSubstApp_h

// end of file
