// WinSubst application.
// Copyright (c) 2004 by Elijah Zarezky,
// All rights reserved.

// WinSubstApp.h - interface of the CWinSubstApp class

// initially generated by AfxScratch v1.0.2297 on 25.07.2004 at 13:26:11
// visit http://home.peterstar.ru/zarezky/projects/afx_scratch.html for more info

#if !defined(__WinSubstApp_h)
#define __WinSubstApp_h

#if defined(_MSC_VER) && (_MSC_VER > 1000)
#pragma once
#endif	// _MSC_VER

class CWinSubstApp: public CWinApp
{
	DECLARE_DYNAMIC(CWinSubstApp)
	DECLARE_MESSAGE_MAP()

// construction/destruction
public:
	CWinSubstApp(void);
	virtual ~CWinSubstApp(void);

// operations
public:
	HICON LoadSmIcon(LPCTSTR pszResName);
	void GetVersionString(CString& strDest);

// overridables
public:
	virtual BOOL InitInstance(void);

// diagnostic services
#if defined(_DEBUG)
public:
	virtual void AssertValid(void) const;
	virtual void Dump(CDumpContext& dumpCtx) const;
#endif
};

#endif	// __WinSubstApp_h

// end of file
